import datetime
import os
import re
import traceback
from pathlib import Path
import pandas as pd
import numpy as np
import anthropic
from anthropic import Anthropic

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOTENV_PATH = PROJECT_ROOT / '.env'

# The results workbook's 'season' column has gone through two rounds of Excel
# corruption: short codes like "02/03" were first misread as dates with no
# year (e.g. "2026-02-03"), then a manual fix reformatted those dates back to
# text but kept the stray "2026" year, producing "MM/26" labels instead of
# the true season code. Row counts confirm these are the same 9 real
# seasons, just mislabeled, so the remap is a straight lookup.
SEASON_REMAP = {
    '02/26': '02/03',
    '03/26': '03/04',
    '04/26': '04/05',
    '07/26': '07/08',
    '08/26': '08/09',
    '09/26': '09/10',
    '10/26': '10/11',
    '11/26': '11/12',
    '12/26': '12/13',
}


def normalize_season(value):
    """
    Normalize a raw 'season' cell from the results workbook to a clean
    season code, undoing known Excel corruption patterns.
    """
    if isinstance(value, datetime.date):
        # Covers datetime.date, datetime.datetime, and pd.Timestamp
        return f"{value.month:02d}/{value.day:02d}"

    text = str(value).strip()
    return SEASON_REMAP.get(text, text)


def load_dotenv(dotenv_path=None):
    path = Path(dotenv_path or DOTENV_PATH)
    if not path.exists():
        return

    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


load_dotenv()

# Reports are generated by calling the Anthropic API directly. This used to go
# through the AgentRouter proxy (with a second proxy as a fallback base_url);
# both are gone, along with the base_url overrides that pointed at them.
# Sonnet 5 over Opus for this: the facts are all supplied, so there is no hard
# reasoning to pay for — it is a writing job, and Sonnet handles it at roughly
# half the cost per report.
DEFAULT_ANTHROPIC_MODEL = 'claude-sonnet-5'
# Note this is env-overridable: a stale ANTHROPIC_MODEL left over from the
# proxy era (it routed non-Anthropic ids) will silently win over the default
# and every call will fail against the real API.
ANTHROPIC_MODEL = os.getenv('ANTHROPIC_MODEL', DEFAULT_ANTHROPIC_MODEL)
# Generous rather than long: thinking shares the output budget on current
# models, and this was previously low enough that reasoning could consume the
# whole allowance before any report text was emitted. Report length is
# controlled by the prompt, not by starving max_tokens.
ANTHROPIC_MAX_TOKENS = int(os.getenv('ANTHROPIC_MAX_TOKENS', '8000'))
OPENAI_MAX_TOKENS = int(os.getenv('OPENAI_MAX_TOKENS', '8000'))
GEMINI_MAX_TOKENS = int(os.getenv('GEMINI_MAX_TOKENS', '8000'))


def get_ai_provider():
    provider = (os.getenv('AI_PROVIDER', 'anthropic') or 'anthropic').strip().lower()
    if provider not in {'anthropic', 'openai', 'gemini'}:
        raise ValueError(
            "AI_PROVIDER must be one of: anthropic, openai, gemini."
        )
    return provider


def get_anthropic_api_key():
    api_key = os.getenv('ANTHROPIC_API_KEY', '').strip()
    if not api_key:
        raise ValueError(
            'Anthropic API key is not configured. Set ANTHROPIC_API_KEY in your '
            'environment or .env before generating reports.'
        )
    return api_key


def get_openai_api_key():
    api_key = os.getenv('OPENAI_API_KEY', '').strip()
    if not api_key:
        raise ValueError(
            'OpenAI API key is not configured. Set OPENAI_API_KEY in your '
            'environment or .env before generating reports.'
        )
    return api_key


def get_gemini_api_key():
    api_key = os.getenv('GEMINI_API_KEY', '').strip()
    if not api_key:
        raise ValueError(
            'Gemini API key is not configured. Set GEMINI_API_KEY in your '
            'environment or .env before generating reports.'
        )
    return api_key


def get_api_key_for_provider(provider=None):
    provider = (provider or get_ai_provider()).strip().lower()
    if provider == 'anthropic':
        return get_anthropic_api_key()
    if provider == 'openai':
        return get_openai_api_key()
    if provider == 'gemini':
        return get_gemini_api_key()
    raise ValueError(f'Unsupported AI provider: {provider}')

def get_npfl_data(force_refresh=False):
    """
    Load every NPFL match from the database as a DataFrame.

    Read fresh on every call. There used to be a 24-hour LocMem cache here,
    which is why edits took a day to appear — and worse, LocMem is per-process,
    so under gunicorn one worker could serve stale rows long after another had
    been refreshed.

    Caching is unnecessary now: `.values()` returns plain rows straight from the
    database instead of building ~8,000 Match and Team model instances that are
    immediately discarded, which is about four times faster (105ms vs 426ms on
    the current dataset). This is called once per comparison request.

    `force_refresh` is kept because eight call sites pass it, but every read is
    already fresh, so it does nothing.
    """
    from dashboard.models import Match

    if not Match.objects.exists():
        raise ValueError('No match data available in the database. Run the importer to populate Match records.')

    # order_by('id') states what the code already relied on: rows are inserted
    # in match order by the Excel importer and appended by the admin, so id
    # order IS chronological. Match.date is empty, so it cannot be used, and an
    # unordered queryset has no guaranteed SQL order at all — losing that order
    # would silently scramble every "last 5" form guide.
    qs = Match.objects.order_by('id').values(
        'season', 'match_name', 'home__name', 'away__name',
        'home_goal', 'away_goal', 'date', 'stadium',
    )
    df = pd.DataFrame.from_records(qs)
    if df.empty:
        raise ValueError('No match data available in the database. Run the importer to populate Match records.')

    df = df.rename(columns={'home__name': 'home', 'away__name': 'away'})
    df['home_goal'] = pd.to_numeric(df['home_goal'], errors='coerce')
    df['away_goal'] = pd.to_numeric(df['away_goal'], errors='coerce')
    return df

def get_unique_teams():
    """
    Get a sorted list of all unique teams.
    """
    try:
        df = get_npfl_data()
        home_teams = df['home'].dropna().unique()
        away_teams = df['away'].dropna().unique()
        all_teams = sorted(list(set(home_teams) | set(away_teams)))
        return all_teams
    except Exception:
        return []

def get_all_seasons():
    """
    Get a sorted list of all season codes present in the match data.
    """
    try:
        df = get_npfl_data()
        return sorted(df['season'].dropna().unique().tolist())
    except Exception:
        return []

def get_team_home_away_splits(season=None):
    """
    Compute each team's real home/away Played/Win/Draw/Loss/Goals counts from
    completed matches, plus season totals and points, optionally restricted
    to a single season.
    """
    df = get_npfl_data()
    df = df.dropna(subset=['home_goal', 'away_goal'])
    if season:
        df = df[df['season'] == season]

    splits = []
    for team in get_unique_teams():
        home_df = df[df['home'] == team]
        away_df = df[df['away'] == team]

        home_win = int((home_df['home_goal'] > home_df['away_goal']).sum())
        home_draw = int((home_df['home_goal'] == home_df['away_goal']).sum())
        home_loss = int((home_df['home_goal'] < home_df['away_goal']).sum())
        home_gf = int(home_df['home_goal'].sum())
        home_ga = int(home_df['away_goal'].sum())

        away_win = int((away_df['away_goal'] > away_df['home_goal']).sum())
        away_draw = int((away_df['away_goal'] == away_df['home_goal']).sum())
        away_loss = int((away_df['away_goal'] < away_df['home_goal']).sum())
        away_gf = int(away_df['away_goal'].sum())
        away_ga = int(away_df['home_goal'].sum())

        total_win = home_win + away_win
        total_draw = home_draw + away_draw
        total_loss = home_loss + away_loss
        total_gf = home_gf + away_gf
        total_ga = home_ga + away_ga

        splits.append({
            'team': team,
            'home_played': len(home_df),
            'home_win': home_win,
            'home_draw': home_draw,
            'home_loss': home_loss,
            'home_gf': home_gf,
            'home_ga': home_ga,
            'away_played': len(away_df),
            'away_win': away_win,
            'away_draw': away_draw,
            'away_loss': away_loss,
            'away_gf': away_gf,
            'away_ga': away_ga,
            'total_win': total_win,
            'total_draw': total_draw,
            'total_loss': total_loss,
            'total_gf': total_gf,
            'total_ga': total_ga,
            'total_gd': total_gf - total_ga,
            'points': total_win * 3 + total_draw,
        })

    return splits

def determine_match_result(row, team):
    """
    Determine W/D/L for a team in a given match row.
    """
    if pd.isna(row['home_goal']) or pd.isna(row['away_goal']):
        return None
    
    home_g = int(row['home_goal'])
    away_g = int(row['away_goal'])
    
    if row['home'] == team:
        if home_g > away_g:
            return 'W'
        elif home_g < away_g:
            return 'L'
        else:
            return 'D'
    elif row['away'] == team:
        if away_g > home_g:
            return 'W'
        elif away_g < home_g:
            return 'L'
        else:
            return 'D'
    return None

def team_recent_matches(df, team, n=5):
    """
    A team's last n completed matches, chronologically ordered (df is expected
    to already be in id/insertion order, per get_npfl_data). Naturally crosses
    season boundaries: a team with only 1 game in a new season and n-1 or more
    from the previous season still gets a full n-game window.
    """
    team_games = df[(df['home'] == team) | (df['away'] == team)].copy()
    return team_games.dropna(subset=['home_goal', 'away_goal']).tail(n)

def get_team_form(df, team, n=5):
    """
    Retrieve the last n completed matches for a team and compute their form string (e.g. WWDLD).
    """
    completed = team_recent_matches(df, team, n)

    results = []
    games_list = []
    for idx, row in completed.iterrows():
        res = determine_match_result(row, team)
        results.append(res)
        games_list.append({
            'season': str(row['season']),
            'home': row['home'],
            'away': row['away'],
            'home_goal': int(row['home_goal']),
            'away_goal': int(row['away_goal']),
            'result': res
        })
    
    form_string = ''.join([r for r in results if r])
    return form_string, games_list

def perform_comparison(team1, team2):
    """
    Perform a complete head-to-head analysis between team1 and team2.
    """
    df = get_npfl_data()
    
    # Filter matches between team1 and team2
    h2h_df = df[((df['home'] == team1) & (df['away'] == team2)) | 
                ((df['home'] == team2) & (df['away'] == team1))].copy()
    
    # Exclude matches that are not played yet (missing scores)
    completed_h2h = h2h_df.dropna(subset=['home_goal', 'away_goal']).copy()
    
    # 1. H2H record counts
    team1_wins = 0
    team2_wins = 0
    draws = 0
    
    for idx, row in completed_h2h.iterrows():
        h_g = int(row['home_goal'])
        a_g = int(row['away_goal'])
        if h_g == a_g:
            draws += 1
        elif row['home'] == team1:
            if h_g > a_g:
                team1_wins += 1
            else:
                team2_wins += 1
        elif row['home'] == team2:
            if h_g > a_g:
                team2_wins += 1
            else:
                team1_wins += 1
                
    total_matches = len(completed_h2h)
    
    # 2. Total Goals Scored against each other
    team1_goals = 0
    team2_goals = 0
    
    for idx, row in completed_h2h.iterrows():
        h_g = int(row['home_goal'])
        a_g = int(row['away_goal'])
        if row['home'] == team1:
            team1_goals += h_g
            team2_goals += a_g
        else:
            team2_goals += h_g
            team1_goals += a_g
            
    # 3. Average goals
    avg_scored_t1 = team1_goals / total_matches if total_matches > 0 else 0.0
    avg_conceded_t1 = team2_goals / total_matches if total_matches > 0 else 0.0
    avg_scored_t2 = team2_goals / total_matches if total_matches > 0 else 0.0
    avg_conceded_t2 = team1_goals / total_matches if total_matches > 0 else 0.0
    
    # 4. Goals Distribution by Season
    # Sum the goals for each season in matches between the two
    completed_h2h['total_goals'] = completed_h2h['home_goal'] + completed_h2h['away_goal']
    season_goals = completed_h2h.groupby('season')['total_goals'].sum().reset_index()
    season_goals['total_goals'] = season_goals['total_goals'].astype(int)
    season_goals_sorted = season_goals.sort_values(by='total_goals', ascending=False).to_dict(orient='records')
    
    # 5. Goals Distribution by Season per Team
    # We want to see how many goals team1 scored and team2 scored in each season
    team1_season_goals = {}
    team2_season_goals = {}
    all_seasons = sorted(completed_h2h['season'].unique())
    
    for season in all_seasons:
        t1_s_g = 0
        t2_s_g = 0
        season_matches = completed_h2h[completed_h2h['season'] == season]
        for idx, row in season_matches.iterrows():
            h_g = int(row['home_goal'])
            a_g = int(row['away_goal'])
            if row['home'] == team1:
                t1_s_g += h_g
                t2_s_g += a_g
            else:
                t2_s_g += h_g
                t1_s_g += a_g
        team1_season_goals[season] = t1_s_g
        team2_season_goals[season] = t2_s_g
        
    # Get last 10 seasons for the side-by-side comparison
    last_10_seasons = all_seasons[-10:]
    goals_per_team_season = []
    for s in last_10_seasons:
        goals_per_team_season.append({
            'season': s,
            f'{team1}_goals': team1_season_goals.get(s, 0),
            f'{team2}_goals': team2_season_goals.get(s, 0)
        })
        
    # 6. Team Forms (Overall)
    t1_form_str, t1_recent_games = get_team_form(df, team1)
    t2_form_str, t2_recent_games = get_team_form(df, team2)
    
    # 7. Raw match details
    raw_matches = []
    for idx, row in completed_h2h.iterrows():
        raw_matches.append({
            'season': str(row['season']),
            'home': row['home'],
            'away': row['away'],
            'home_goal': int(row['home_goal']),
            'away_goal': int(row['away_goal']),
            'match_name': row.get('match_name', f"{row['home']} vs {row['away']}")
        })
        
    # Reverse raw_matches to show latest first
    raw_matches.reverse()
    
    return {
        'team1': team1,
        'team2': team2,
        'total_matches': total_matches,
        'team1_wins': team1_wins,
        'team2_wins': team2_wins,
        'draws': draws,
        'team1_goals': team1_goals,
        'team2_goals': team2_goals,
        'avg_scored_t1': avg_scored_t1,
        'avg_conceded_t1': avg_conceded_t1,
        'avg_scored_t2': avg_scored_t2,
        'avg_conceded_t2': avg_conceded_t2,
        'season_goals': season_goals_sorted,
        'goals_per_team_season': goals_per_team_season,
        'team1_form': t1_form_str,
        'team1_recent_games': t1_recent_games,
        'team2_form': t2_form_str,
        'team2_recent_games': t2_recent_games,
        'raw_matches': raw_matches
    }


def _format_recent_games(games):
    if not games:
        return 'No recent completed games available.'

    lines = []
    for game in games[:5]:
        lines.append(
            f"{game['season']}: {game['home']} {game['home_goal']}-{game['away_goal']} {game['away']} ({game['result']})"
        )
    return '\n'.join(lines)


def _format_recent_meetings(raw_matches, limit=5):
    """
    The last few times these two actually played each other, newest first.

    perform_comparison already reverses raw_matches into newest-first order, so
    this is a plain slice. Distinct from the aggregate H2H record: 18 meetings
    since 2005 says something very different from how the last three went.
    """
    if not raw_matches:
        return 'These two have no completed meetings on record.'

    return '\n'.join(
        f"{m['season']}: {m['home']} {m['home_goal']}-{m['away_goal']} {m['away']}"
        for m in raw_matches[:limit]
    )


REPORT_SYSTEM_PROMPT = (
    'You are a football writer for MIAS covering the NPFL in Oxford British '
    'English. Write like a newsroom reporter, not an AI. Keep the language '
    'natural, direct and authoritative, with one sentence per paragraph and a '
    'new line after every full stop for readability. Use short paragraphs, '
    'varied sentence lengths, one main idea per paragraph, and clear newsroom '
    'flow. Prefer active voice, precise verbs and BBC-style clarity. Avoid '
    'obvious AI transitions, padded context, repetitive conclusions, inflated '
    'adjectives, or formulaic language. Do not use headings, bullet points or '
    'obvious AI phrasing. Every sentence should carry a fact or a judgement '
    'the reader did not have before it.'
)


def _normalise_report_lines(report_text):
    """Force a BBC-style newsroom rhythm: one sentence, then a visible gap."""
    if not report_text:
        return report_text

    cleaned = ' '.join(report_text.split())
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', cleaned) if s.strip()]
    return '\n\n'.join(sentences)


def generate_expert_report(team1, team2, comparison_data):
    provider = get_ai_provider()
    api_key = get_api_key_for_provider(provider)

    recent_team1 = _format_recent_games(comparison_data.get('team1_recent_games', []))
    recent_team2 = _format_recent_games(comparison_data.get('team2_recent_games', []))
    recent_meetings = _format_recent_meetings(comparison_data.get('raw_matches', []))
    season_summaries = comparison_data.get('season_goals', [])[:5]
    season_summary_text = ', '.join(
        [f"{item['season']} ({item['total_goals']} goals)" for item in season_summaries]
    ) or 'No season goal summary available.'

    # The facts are deliberately a compact block rather than a long bulleted
    # list of one fact per line: the shape of a prompt bleeds into the shape of
    # the answer, and the old bullet wall had the model walking the list and
    # restating each entry in turn. The length steer is a soft range, not a
    # hard word cap, which starves the writing instead of tightening it.
    prompt = f"""Head-to-head record, {team1} vs {team2}:
{comparison_data['total_matches']} meetings — {team1} {comparison_data['team1_wins']} wins, {team2} {comparison_data['team2_wins']} wins, {comparison_data['draws']} draws.
Goals: {team1} {comparison_data['team1_goals']} ({comparison_data['avg_scored_t1']:.2f} scored, {comparison_data['avg_conceded_t1']:.2f} conceded per meeting); {team2} {comparison_data['team2_goals']} ({comparison_data['avg_scored_t2']:.2f} scored, {comparison_data['avg_conceded_t2']:.2f} conceded per meeting).
Highest-scoring seasons between them: {season_summary_text}

Their most recent meetings (newest first):
{recent_meetings}

{team1} last five league matches ({comparison_data['team1_form']}), newest last:
{recent_team1}

{team2} last five league matches ({comparison_data['team2_form']}), newest last:
{recent_team2}

Write a match preview in Oxford British English, following the MIAS newsroom writing guide. Keep it to four or five short paragraphs, roughly 400-550 words, with one sentence per paragraph and a new line after every full stop. no headings, no bullet points, and no obvious AI filler.

Use the structure of a strong football preview: open with the key angle of the fixture and why it matters; then cover the all-time head-to-head record as separate context from the recent meetings; assess each side's last five league matches with specific results and what they suggest; explain what the goal averages say about how each team plays; and finish with a clear judgement on who is better placed and why.

Follow these MIAS rules: short paragraphs, varied sentence lengths, one main idea per paragraph, active voice, precise verbs and no obvious AI transitions. Use each fact once. Do not repeat the same facts in different language. Do not add generic filler such as 'in a significant development' or 'it has been revealed that'. Do not summarise your own points at the end. Keep the copy sounding like a knowledgeable football journalist, not a machine.

Treat the all-time record and the recent meetings as separate points, and say where they disagree. Name the specific results in form, and keep the closing judgement grounded in those facts rather than a generic prediction.
"""

    if provider == 'anthropic':
        client = Anthropic(api_key=api_key, timeout=120.0)
        try:
            response = client.messages.create(
                model=ANTHROPIC_MODEL,
                max_tokens=ANTHROPIC_MAX_TOKENS,
                output_config={'effort': 'medium'},
                system=REPORT_SYSTEM_PROMPT,
                messages=[{'role': 'user', 'content': prompt}],
            )
        except anthropic.AuthenticationError:
            raise ValueError('Anthropic rejected the API key. Check ANTHROPIC_API_KEY.')
        except anthropic.RateLimitError:
            raise ValueError('Anthropic is rate limiting this key. Try again shortly.')
        except anthropic.APIStatusError as exc:
            raise ValueError(f'Anthropic returned an error ({exc.status_code}). Try again later.')
        except anthropic.APIConnectionError:
            raise ValueError('Could not reach Anthropic. Check the server network connection.')

        report_text = '\n\n'.join(
            block.text.strip()
            for block in response.content
            if getattr(block, 'type', None) == 'text' and block.text.strip()
        ).strip()

        if not report_text:
            raise ValueError('Anthropic returned an empty report.')
        return _normalise_report_lines(report_text)

    if provider == 'openai':
        from openai import OpenAI

        client = OpenAI(api_key=api_key, timeout=120.0)
        try:
            response = client.responses.create(
                model=os.getenv('OPENAI_MODEL', 'gpt-5.6-sol'),
                input=[
                    {'role': 'system', 'content': REPORT_SYSTEM_PROMPT},
                    {'role': 'user', 'content': prompt},
                ],
                max_output_tokens=int(os.getenv('OPENAI_MAX_TOKENS', OPENAI_MAX_TOKENS)),
            )
        except Exception as exc:  # pragma: no cover - provider-specific error path
            raise ValueError(f'OpenAI returned an error: {exc}') from exc

        text = getattr(response, 'output_text', '')
        if not text:
            for item in getattr(response, 'output', []):
                if hasattr(item, 'content'):
                    for block in item.content:
                        if getattr(block, 'type', None) == 'output_text':
                            text += getattr(block, 'text', '')
                            break
        if not text:
            raise ValueError('OpenAI returned an empty report.')
        return _normalise_report_lines(text)

    if provider == 'gemini':
        try:
            import google.generativeai as genai
        except Exception as exc:  # pragma: no cover
            raise ValueError('Gemini SDK is not installed. Install google-generativeai.') from exc

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(model_name=os.getenv('GEMINI_MODEL', 'gemini-1.5-flash'))
        try:
            response = model.generate_content(
                REPORT_SYSTEM_PROMPT + '\n\n' + prompt,
                generation_config={'max_output_tokens': int(os.getenv('GEMINI_MAX_TOKENS', GEMINI_MAX_TOKENS))}
            )
        except Exception as exc:  # pragma: no cover
            raise ValueError(f'Gemini returned an error: {exc}') from exc

        text = getattr(response, 'text', '')
        if not text and hasattr(response, 'candidates'):
            for candidate in response.candidates:
                if getattr(candidate, 'content', None):
                    text = ''.join(part.text for part in candidate.content.parts if getattr(part, 'text', None))
                    break
        if not text:
            raise ValueError('Gemini returned an empty report.')
        return _normalise_report_lines(text)

    raise ValueError(f'Unsupported AI provider: {provider}')
