# Generated by Django 6.1 on 2026-08-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("logo", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(blank=True, max_length=32)),
                ("match_name", models.CharField(blank=True, max_length=255)),
                ("home_goal", models.IntegerField(blank=True, null=True)),
                ("away_goal", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("stadium", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "away",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="away_matches",
                        to="dashboard.team",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_matches",
                        to="dashboard.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["season"], name="dashboard_m_season_6e7919_idx"
                    ),
                    models.Index(
                        fields=["home"], name="dashboard_m_home_id_da404e_idx"
                    ),
                    models.Index(
                        fields=["away"], name="dashboard_m_away_id_fdc5ef_idx"
                    ),
                ],
            },
        ),
    ]
