# Generated by Django 6.1 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('dashboard', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='TeamComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.CharField(max_length=200)),
                ('team_two', models.CharField(max_length=200)),
                ('report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team_one', 'team_two'), name='unique_team_comparison_report')],
            },
        ),
    ]
