# Generated by Django 6.0.3 on 2026-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_teamcomparisonreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamcomparisonreport",
            name="ai_generated",
            field=models.BooleanField(default=True),
        ),
    ]
