# Generated by Django 6.1 on 2026-08-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0002_teamcomparisonreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(default="26/27", max_length=32)),
                ("version_label", models.CharField(max_length=100)),
                ("match_day_computed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_latest", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeasonFixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(default="26/27", max_length=32)),
                ("match_day", models.IntegerField()),
                (
                    "away",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sc_away_fixtures",
                        to="dashboard.team",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sc_home_fixtures",
                        to="dashboard.team",
                    ),
                ),
            ],
            options={
                "ordering": ["match_day"],
                "unique_together": {("season", "home", "away")},
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_win_pct", models.FloatField()),
                ("draw_pct", models.FloatField()),
                ("away_win_pct", models.FloatField()),
                ("predicted_result", models.CharField(max_length=10)),
                ("confidence", models.FloatField()),
                ("home_form_score", models.FloatField(default=0)),
                ("away_form_score", models.FloatField(default=0)),
                ("h2h_home_rate", models.FloatField(default=0)),
                ("h2h_away_rate", models.FloatField(default=0)),
                ("h2h_draw_rate", models.FloatField(default=0)),
                ("home_venue_strength", models.FloatField(default=0)),
                ("away_venue_strength", models.FloatField(default=0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="supercomputer.predictionsnapshot",
                    ),
                ),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="supercomputer.seasonfixture",
                    ),
                ),
            ],
            options={
                "unique_together": {("snapshot", "fixture")},
            },
        ),
    ]
