# Generated by Django 5.2.17 on 2026-08-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_teamcomparisonreport_ai_generated"),
        ("supercomputer", "0004_prediction_away_transfer_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSeasonProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(default="26/27", max_length=32)),
                ("title_pct", models.FloatField(default=0.0)),
                ("top3_pct", models.FloatField(default=0.0)),
                ("relegation_pct", models.FloatField(default=0.0)),
                ("expected_points", models.FloatField(default=0.0)),
                ("best_points", models.IntegerField(default=0)),
                ("worst_points", models.IntegerField(default=0)),
                ("avg_goal_diff", models.FloatField(default=0.0)),
                ("avg_position", models.FloatField(default=0.0)),
                ("simulations_count", models.IntegerField(default=1000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_projections",
                        to="dashboard.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-expected_points", "-avg_goal_diff"],
                "unique_together": {("season", "team")},
            },
        ),
    ]
