# Generated by Django 5.2.17 on 2026-08-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_teamcomparisonreport_ai_generated"),
        ("supercomputer", "0005_teamseasonprojection"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamCareerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts", models.IntegerField(default=0)),
                ("played", models.IntegerField(default=0)),
                ("home_win", models.IntegerField(default=0)),
                ("home_draw", models.IntegerField(default=0)),
                ("home_loss", models.IntegerField(default=0)),
                ("away_win", models.IntegerField(default=0)),
                ("away_draw", models.IntegerField(default=0)),
                ("away_loss", models.IntegerField(default=0)),
                ("home_gf", models.IntegerField(default=0)),
                ("home_ga", models.IntegerField(default=0)),
                ("away_gf", models.IntegerField(default=0)),
                ("away_ga", models.IntegerField(default=0)),
                ("total_win", models.IntegerField(default=0)),
                ("total_draw", models.IntegerField(default=0)),
                ("total_loss", models.IntegerField(default=0)),
                ("total_gf", models.IntegerField(default=0)),
                ("total_ga", models.IntegerField(default=0)),
                ("total_gd", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("source_rank", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_stats",
                        to="dashboard.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Team career stats",
                "ordering": ["-points", "-total_gd"],
            },
        ),
    ]
