# Generated by Django 5.2.17 on 2026-08-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supercomputer", "0007_remove_prediction_away_form_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonfixture",
            name="away_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seasonfixture",
            name="home_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
