# Generated by Django 5.2.17 on 2026-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supercomputer", "0011_prediction_scoreline_grid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchDayVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(default="26/27", max_length=32)),
                ("match_day", models.IntegerField()),
                ("is_unlocked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Match day visibility",
                "ordering": ["match_day"],
                "unique_together": {("season", "match_day")},
            },
        ),
    ]
