# Generated by Django 5.2.17 on 2026-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supercomputer", "0013_seed_match_day_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonSummaryOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("games", models.PositiveIntegerField(default=0)),
                ("home_wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("away_wins", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
